IF NOT EXISTS (SELECT name FROM sys.tables where name = 'DimZona')
BEGIN
CREATE TABLE [dbo].[DimZona](
	[ZonaKey] [int] IDENTITY(1,1) NOT NULL,
	[ZonaId] [numeric](5, 0) NOT NULL,
	[Zona] [varchar](50) NULL
 CONSTRAINT [PK_DimZona] PRIMARY KEY CLUSTERED 
(
	[ZonaKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--Retirar do script

CREATE NONCLUSTERED INDEX [NonClusteredIndex-ZonaId] ON [dbo].[DimZona]
(
	[ZonaId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

-----

END
