IF NOT EXISTS (SELECT name FROM sys.tables where name = 'ClientesDuplicatesInsideSources')
CREATE TABLE [dbo].ClientesDuplicatesInsideSources(
	[_key_in] [int] NULL,
	[_key_out] [int] NULL,
	[nome] [varchar](55) NOT NULL,
	[ncontribuinte] [varchar](20) NOT NULL,
	[saldo] [numeric](19, 6) NOT NULL,
	[moeda] [varchar](11) NOT NULL,
	[fax] [varchar](60) NOT NULL,
	[telefone] [varchar](60) NOT NULL,
	[contacto] [varchar](30) NOT NULL,
	[morada] [varchar](55) NOT NULL,
	[localidade] [varchar](43) NOT NULL,
	[codpostal] [varchar](45) NOT NULL,
	[zona] [numeric](5, 0) NULL,
	[tipo] [varchar](20) NOT NULL,
	[vendedor] [numeric](4, 0) NOT NULL,
	[vencimento] [numeric](3, 0) NOT NULL,
	[plafond] [numeric](19, 6) NOT NULL,
	[nib] [varchar](28) NOT NULL,
	[segmento] [varchar](25) NOT NULL,
	[email] [varchar](45) NOT NULL,
	[centrocusto] [varchar](20) NOT NULL,
	[tlmvl] [varchar](45) NOT NULL,
	[data_criacao] [datetime] NOT NULL,
	[hora_criacao] [varchar](8) NOT NULL,
	[data_ult_gravacao] [datetime] NOT NULL,
	[hora_ult_gravacao] [varchar](8) NOT NULL,

	[nome_clean] [varchar](55) NOT NULL,
	[ncontribuinte_clean] [varchar](20) NOT NULL,
	--[saldo_clean] [numeric](19, 6) NOT NULL,
	[moeda_clean] [varchar](11) NOT NULL,
	[fax_clean] [varchar](60) NOT NULL,
	[telefone_clean] [varchar](60) NOT NULL,
	[contacto_clean] [varchar](30) NOT NULL,
	[morada_clean] [varchar](55) NOT NULL,
	[localidade_clean] [varchar](43) NOT NULL,
	[codpostal_clean] [varchar](45) NOT NULL,
	--[zona_clean] [numeric](5, 0) NULL,
	[tipo_clean] [varchar](20) NOT NULL,
	--[vendedor_clean] [numeric](4, 0) NOT NULL,	
	--[vencimento_clean] [numeric](3, 0) NOT NULL,
	--[plafond_clean] [numeric](19, 6) NOT NULL,
	[nib_clean] [varchar](28) NOT NULL,
	[segmento_clean] [varchar](25) NOT NULL,
	[email_clean] [varchar](45) NOT NULL,
	[centrocusto_clean] [varchar](20) NOT NULL,
	[tlmvl_clean] [varchar](45) NOT NULL,	
	--[data_criacao_clean] [datetime] NOT NULL,
	--[hora_criacao_clean] [varchar](8) NOT NULL,
	--[data_ult_gravacao_clean] [datetime] NOT NULL,
	--[hora_ult_gravacao_clean] [varchar](8) NOT NULL,

	[_Similarity][real] NULL,
	[_Similarity_Nome][real] NULL,
	[_Similarity_NContribuinte][real] NULL,
	[_Similarity_Telefone][real] NULL,
	[_Similarity_Contacto][real] NULL,
	[_Similarity_Morada][real] NULL,
	[_Similarity_Localidade][real] NULL,
	[_Similarity_CodPostal][real] NULL,
	--[_Similarity_Zona][real] NULL,
	[_Similarity_Tipo][real] NULL,
	--[_Similarity_Vendedor][real] NULL,
	[_Similarity_NIB][real] NULL,
	_Similarity_Segmento [real] NULL,
	_Similarity_Email[real] NULL,
	_Similarity_CentroCusto[real] NULL,
	_Similarity_Telemovel[real] NULL,
	_Similarity_Fax[real] NULL,
	_Similarity_Moeda[real] NULL
)
ELSE
	TRUNCATE TABLE ClientesDuplicatesInsideSources