IF NOT EXISTS (SELECT name FROM sys.tables where name = 'ClientesDuplicatesBetweenSources')
CREATE TABLE [dbo].ClientesDuplicatesBetweenSources(
	[nome (Input)] [varchar](55) NOT NULL,
	--[numero (Input)] [numeric](10, 0) NOT NULL,
	[ncontribuinte (Input)] [varchar](20) NOT NULL,
	[saldo (Input)] [numeric](19, 6) NOT NULL,
	[moeda (Input)] [varchar](11) NOT NULL,
	[fax (Input)] [varchar](60) NOT NULL,
	[telefone (Input)] [varchar](60) NOT NULL,
	[contacto (Input)] [varchar](30) NOT NULL,
	[morada (Input)] [varchar](55) NOT NULL,
	[localidade (Input)] [varchar](43) NOT NULL,
	[codpostal (Input)] [varchar](45) NOT NULL,
	[zona (Input)] [numeric](5, 0) NULL,
	[tipo (Input)] [varchar](20) NOT NULL,
	[vendedor (Input)] [numeric](4, 0) NOT NULL,
	[vencimento (Input)] [numeric](3, 0) NOT NULL,
	[plafond (Input)] [numeric](19, 6) NOT NULL,
	[nib (Input)] [varchar](28) NOT NULL,
	[segmento (Input)] [varchar](25) NOT NULL,
	[email (Input)] [varchar](45) NOT NULL,
	[centrocusto (Input)] [varchar](20) NOT NULL,
	[tlmvl (Input)] [varchar](45) NOT NULL,
	[data_criacao (Input)] [datetime] NOT NULL,
	[hora_criacao (Input)] [varchar](8) NOT NULL,
	[data_ult_gravacao (Input)] [datetime] NOT NULL,
	[hora_ult_gravacao (Input)] [varchar](8) NOT NULL,

	[nome (Matched)] [varchar](55) NOT NULL,
	--[numero (Matched)] [numeric](10, 0) NOT NULL,
	[ncontribuinte  (Matched)] [varchar](20) NOT NULL,
	[saldo (Matched)] [numeric](19, 6) NOT NULL,
	[moeda (Matched)] [varchar](11) NOT NULL,
	[fax (Matched)] [varchar](60) NOT NULL,
	[telefone (Matched)] [varchar](60) NOT NULL,
	[contacto (Matched)] [varchar](30) NOT NULL,
	[morada (Matched)] [varchar](55) NOT NULL,
	[localidade (Matched))] [varchar](43) NOT NULL,
	[codpostal (Matched)] [varchar](45) NOT NULL,
	[zona (Matched)] [numeric](5, 0) NULL,
	[tipo (Matched)] [varchar](20) NOT NULL,
	[vendedor (Matched)] [numeric](4, 0) NOT NULL,	
	[vencimento (Matched)] [numeric](3, 0) NOT NULL,
	[plafond (Matched)] [numeric](19, 6) NOT NULL,
	[nib (Matched)] [varchar](28) NOT NULL,
	[segmento (Matched)] [varchar](25) NOT NULL,
	[email (Matched)] [varchar](45) NOT NULL,
	[centrocusto (Matched)] [varchar](20) NOT NULL,
	[tlmvl (Matched)] [varchar](45) NOT NULL,	
	[data_criacao (Matched)] [datetime] NOT NULL,
	[hora_criacao (Matched)] [varchar](8) NOT NULL,
	[data_ult_gravacao (Matched)] [datetime] NOT NULL,
	[hora_ult_gravacao (Matched)] [varchar](8) NOT NULL,

	[_Similarity][real] NULL,
	[_Similarity_Nome][real] NULL,
	[_Similarity_NContribuinte][real] NULL,
	[_Similarity_Telefone][real] NULL,
	[_Similarity_Contacto][real] NULL,
	[_Similarity_Morada][real] NULL,
	[_Similarity_Localidade][real] NULL,
	[_Similarity_CodPostal][real] NULL,
	[_Similarity_Zona][real] NULL,
	[_Similarity_Tipo][real] NULL,
	[_Similarity_Vendedor][real] NULL,
	[_Similarity_NIB][real] NULL,
	_Similarity_Segmento [real] NULL,
	_Similarity_Email[real] NULL,
	_Similarity_CentroCusto[real] NULL,
	_Similarity_Telemovel[real] NULL,
	_Similarity_Fax[real] NULL,
	_Similarity_Moeda[real] NULL
)
ELSE
	TRUNCATE TABLE ClientesDuplicatesBetweenSources